### ISSUE TITLE
bx copyright notice...

### ISSUE THREAD

**Issue by bkaradzic** [septag/sx#10]
I noticed your project is using a lot of code from my bx library, but there is little acknowledgement where code came from.

I noticed you're properly acknowledging code that came from STB libraries even thought they are public domain, but not code that came from bx which is BSD-2 and explicitly states that you must keep copyright notice:

```
   1. Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.
```

https://github.com/bkaradzic/bx#license-bsd-2-clause

Please add info around code you copied from bx.

**Comment by septag** [comment]
Done.
Yes, stb's code, I used the whole thing without modifications, unlike your code that was ripped off/refactored and scattered in multiple files. so, sorry I totally forgot.
Please notify me if I missed something in there.

Thank you for your great work
