### ISSUE TITLE
EXC_BAD_ACCESS with job execution

### ISSUE THREAD

**Issue by troughton** [septag/sx#14]
With [a simple change to test_jobs.c](https://github.com/troughton/sx/commit/b49793d0256843aeb3213d7e5104ad0f6cfbb170), execution on macOS fails with an EXC_BAD_ACCESS in `make_fcontext`. The issue can be triggered by dispatching and waiting on multiple separate jobs within an existing job; adding 

```
job = sx_job_dispatch(g_ctx, jobs, 1, 0);
sx_job_wait_and_del(g_ctx, job);
```

after the existing dispatch in `job_fib_fn` is sufficient.

**Comment by troughton** [comment]
My suspicion is this is because `cur_job` is set in the thread-local storage within a job's `fiber_fn` at the start of execution, but may be overwritten when dispatching another job.

**Comment by troughton** [comment]
Storing the source selector fibre on the job and setting it in the TLS before every context switch seems a workable solution: https://github.com/troughton/sx/commit/9cace4b99318da542d4894a2c309bcd0e1554df7

**Comment by septag** [comment]
Sorry for late answer, I was busy with something else and didn't have the time to investigate this.

Ouch. yes you are right. I never actually tested it with this scenario and obviously this thing is not battle-tested.

could you do a PR on this ?
thanks
