### ISSUE TITLE
Cross-compiling from Linux to Windows fails

### ISSUE THREAD

**Issue by rivten** [septag/sx#22]
I was trying to produce a win32 executable of my app using Linux.
Here's the CMake cross-compilation toolchain file I'm using : 

```
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)

include_directories("/usr/x86_64-w64-mingw32/include/")
```

When compiling from Manjaro with this, I'm hitting several issues : 

- In `sx.h`, I probably need to add an include to `string.h` because of `memmove` that is not found.

- https://github.com/septag/sx/blob/master/src/threads.c#L689 this codes probably needs to be surrounded by `#if SX_COMPILER_MSVC` as it seems only msvc defines `__try`

- https://github.com/septag/sx/blob/master/src/os.c#L18 I think `Psapi.h` should be renamed to `psapi.h`. Maybe gcc is case-sensitive when msvc isn't ?

- Also all the `alloca.h `are not found with this setup. But that's maybe because I need to add the compat/msvc as include directory ?

- Finally, there's a weird issue that prevents final linking. 
`/bin/x86_64-w64-mingw32-gcc -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DBOOST_CONTEXT_EXPORT="" @CMakeFiles/sx.dir/includes_ASM.rsp -nostdlib -Wno-deprecated-declarations -o CMakeFiles/sx.dir/asm/ontop_x86_64_ms_pe_masm.asm.obj -c /home/hugo/dev/experiments/sx/asm/ontop_x86_64_ms_pe_masm.asm
x86_64-w64-mingw32-gcc: warning: /home/hugo/dev/experiments/sx/asm/ontop_x86_64_ms_pe_masm.asm: linker input file unused because linking not done`

(EDIT: ok after some investigation, I think that the asm-error is because the cross-compiler `x86_64-w64-mingw32-gcc` doesn't know that an `asm` extension is for assembly files... I tried hacking by changing manually the extension to `.S` with the CMake, but now there's instruction error... Blurhhhh)

Because of the warning, no object file is produced and the final linking step fails. I'm still investigating why, but already [found this](https://stackoverflow.com/questions/2395158/linker-error-linker-input-file-unused-because-linking-not-done-undefined-ref). Not sure if a toolchain to compile asm is missing of something.

Since I'm hitting linker step, I'm guessing that after the last resolution, sx could compile.
Do we want to support cross-compilation like that ?

**Comment by rivten** [comment]
Ok in the end I just disabled the `ASM_SOURCE` and the compilation of `fiber.c` and `jobs.c` when cross-compiling (just like for emscripten) and got it working with the previous tweaks listed !

I haven't try running now, but I'll be sure to try soon.

**Comment by septag** [comment]
I haven't tried compiling with mingw to be honest. I'll get it and give it a try.

About the issues:
- in your case, to find `alloca.h`, you should point to `include/compat/mingw`
- about the asm files, yeah, they probably will fail, because they are masm files, you should try include XXXX_x86_64_ms_pe_gas.asm files intead of masm.

It would be nice if you could make all these changes as a PR

**Comment by septag** [comment]
um.. actually don't bother for PR, I just installed the mingw and I can do that myself.
Thanks

**Comment by septag** [comment]
here u go, 696e3e4d558311282b85e84831b59a80efd220a3

**Comment by rivten** [comment]
Awesome ! Thanks a lot for the reactivity !!
