### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [septag/sx#6]
I would like to point out that identifiers like “[`__min`](https://github.com/septag/sx/blob/8a5056a3449c99fa17e837a2d42156a1eb17c3da/include/sx/sx.h#L95)” and “[`sx__job`](https://github.com/septag/sx/blob/e8a7df4e1cdbcaf381f4fe04a69efa1f07bd4b3c/src/jobs.c#L26)” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by septag** [comment]
could you explain this in more depth ?
do you have problems building it with any other system/compiler ?

I suspect __min/__max may cause problems, but `sx__job` shouldn't have any conflicts with any cpp or 3rdparties. as you may know by now, `sx__` names are used for internal/static usage, and `sx_` are public.

**Comment by elfring** [comment]
How do you think about to avoid that [this software](https://github.com/septag/sx/blob/8a5056a3449c99fa17e837a2d42156a1eb17c3da/include/sx/sx.h#L33 "Update candidate") [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by septag** [comment]
yes I've read it, and I don't think it's gonna be a problem, this is too much neat-picking. 
thanks for the suggestion btw

**Comment by elfring** [comment]
Please [reduce the tampering with the reserved name space](https://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Description for reserved identifiers").
Would you like to [achieve compliance with known programming standards](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?
