### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [septag/sx#7]
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [sx_mutex_init](https://github.com/septag/sx/blob/e8a7df4e1cdbcaf381f4fe04a69efa1f07bd4b3c/src/threads.c#L265)
- [sx_malloc](https://github.com/septag/sx/blob/b0e720d11f060e4adc54b7be29d12323ecc6fefc/include/sx/allocator.h#L114 "Memory allocation") ⇒ [sx__job_create_tdata](https://github.com/septag/sx/blob/e8a7df4e1cdbcaf381f4fe04a69efa1f07bd4b3c/src/jobs.c#L416)

**Comment by septag** [comment]
done

**Comment by elfring** [comment]
I find [the macro name “assert” suspicious for the mentioned use case](https://wiki.sei.cmu.edu/confluence/display/c/PRE31-C.+Avoid+side+effects+in+arguments+to+unsafe+macros#PRE31-C.Avoidsideeffectsinargumentstounsafemacros-NoncompliantCodeExample%28assert%28%29%29 "Avoid side effects in arguments to unsafe macros.").

-----

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?
